### ISSUE TITLE
Refactor role-openldap

### ISSUE THREAD

**Issue by baccenfutter** [blunix/role-openldap#6]
# Todos
- [x] Refactor to latest standards
- [x] Fix deprecation warnings
- [x] Fix Molecule tests

----

Related to: blunix/role-slapd#16
